const strApp = {
  str_product: 'Sản phẩm',
  str_a_quote: 'Giá liên hệ',
  str_search: 'Tìm kiếm',
  str_non_data_product: 'Hiện tại chưa có sản phẩm',
  str_detail_product: 'Chi tiết sản phẩm',
  str_product_description: 'Mô tả sản phẩm',
  str_name_store: 'PHÚC KHANG GEMS',
  str_address_showroom: 'Địa chỉ showroom',
  str_phone: 'Điện thoại',
  str_email: 'Email',
  str_detail_cart: 'Chi tiết giỏ hàng',
  str_gross_product: 'Tổng sản phẩm',
  str_provisional: 'Tạm tính',
  str_country: 'Quốc gia',
  str_province: 'Tỉnh thành',
  str_wards_district: 'Phường xã, Quận huyện',
  str_choose_country: 'Chọn quốc gia',
  str_choose_province: 'Chọn tỉnh thành',
  str_choose_wards_district: 'Chọn phường xã, quận huyện',
  str_input_delivery_address: 'Nhập địa chỉ giao hàng',
  str_input_address: 'Nhập địa chỉ',
  str_input_name: 'Nhập họ tên',
  str_input_phone: 'Nhập số điện thoại',
  str_input_email: 'Nhập email',
  str_phone_error: 'Số điện thoại chưa hợp lệ',
  str_email_error: 'Email chưa hợp lệ',
  str_choose_delivery: 'Chọn hình thức thanh toán',
  str_choose_receive: 'Chọn hình thức nhận hàng',
  str_choose_transfer: 'Chọn nhà vận chuyển',
  str_input_note: 'Nhập ghi chú',
  str_not_input_user_name: 'Bạn chưa nhập họ tên',
  str_not_input_user_phone: 'Bạn chưa nhập số điện thoại',
  str_not_input_address: 'Bạn chưa nhập địa chỉ',
  str_not_choose_country: 'Bạn chưa chọn quốc gia',
  str_not_choose_province: 'Bạn chưa chọn tỉnh thành',
  str_not_choose_wards_district: 'Bạn chưa chọn phường xã, quận huyện',
  str_delivery_charges: 'Phí giao hàng',
  str_store_call: 'chưa được tính trong đơn hàng. Cửa hàng sẽ liên hệ lại với bạn!',
  str_order: 'Đặt hàng',
  str_notification: 'Thông báo',
  str_question_remove_product: 'Bạn có chắc chắn muốn xoá sản phẩm khỏi giỏ hàng không?',
  str_yes: 'Đồng ý',
  str_cancel: 'Hủy',
  str_voucher: 'Mã giảm giá',
  str_input_voucher: 'Nhập mã giảm giá',
  str_not_voucher: 'Mã giảm giá không tồn tại',
  str_store: 'Cửa hàng',
  str_information: 'Thông tin',
  str_contact: 'Liên hệ',
  str_policy: 'Chính sách',
  str_address_shop: 'Địa chỉ',
  str_website: 'Website',
  str_invoice: 'Đơn hàng' ,
  str_account: 'Tài khoản',
  str_order_success: 'Đặt hàng thành công',
  str_order_success_content: 'Bạn đã đặt thành công đơn hàng mã {codeOrder}',
  str_ok: 'Ok',
  str_information_order: 'Để xem thông tin đơn hàng, cũng như các sản phẩm được bảo hành/bảo đảm bởi PHÚC KHANG  sau khi đã mua và trải nghiệm.',
  str_please_input_order: 'Quý khách vui lòng điền thông tin vào mẫu bên dưới:',
  str_phone_number: 'Số điện thoại',
  str_code_order: 'Mã đơn hàng',
  str_input_code_order: 'Nhập mã đơn hàng',
  str_name_customer: 'Họ tên người nhận',
  str_phone_customer: 'Số điện thoại người nhận',
  str_date_order: 'Ngày mua',
  str_gross_monney: 'Tổng tiền thanh toán',
  str_receive: 'Hình thức nhận hàng',
  str_delivery: 'Giao hàng',
  str_received_at_the_shop: 'Nhận tại shop',
  str_status_order: 'Tình trạng đơn hàng',
  str_error_phone_order: 'Số điện thoại chưa đặt hàng',
  str_error_code_order: 'Mã đơn hàng không tồn tại'
}

export default strApp